server:
  port: 8082

spring:
  application:
    name: transaction-service
  datasource:
    url: jdbc:mysql://${DB_HOST:localhost}:${DB_PORT:3306}/financeai_transactions?useSSL=false&allowPublicKeyRetrieval=true&serverTimezone=UTC
    username: ${DB_USER:dev_user}
    password: ${DB_PASSWORD:dev_password}
    driver-class-name: com.mysql.cj.jdbc.Driver
  jpa:
    hibernate:
      ddl-auto: validate
    show-sql: false
    properties:
      hibernate:
        format_sql: true
  flyway:
    enabled: true
    baseline-on-migrate: true

app:
  jwt:
    secret: ${JWT_SECRET:FinanceAI_Secret_Key_Super_Segura_2026_JWT_Token_HS256_Min$}
  services:
    ml:
      url: ${ML_SERVICE_URL:http://ml-service:8000}
    auth:
      url: ${AUTH_SERVICE_URL:http://auth-service:8081}
